### ISSUE TITLE
Port testSuite Jasmine tests to JUnit.

### ISSUE THREAD

**Issue by nicolasstucki** [scala-js/scala-js#2028]
This will allow for cross-compilation of the tests (#2013). JUnit tests will be able to verify themselves against the JVM implementation.

- [x] testSuite/compiler (#2031)
- testSuite/javalib
 - [x] testSuite/javalib/math (#2043)
 - [x] testSuite/javalib/util/Collections (#2085)
 - [x] testSuite/javalib/util/* (#2247)
 - [x] testSuite/javalib/{io|net} (#2047)
 - [x] testSuite/javalib/lang (#2091)
 - [x] testSuite/javalib/time (#2096)
- [x] testSuite/junit (#2024)
- [x] testSuite/niobuffer (#2115)
- [x] testSuite/niocharset (#2038)
- [x] testSuite/scalalib (#2106)
- [x] testSuite/typedarray (#2274)
- [x] testSuite/library
- [x] testSuite/jsinterop (#2280)
- [x] testSuite/compiler (#2278)
- [x] SourceMapTest (#2293)
- [x] tools/../TestRunner (#2296)

**Comment by ummels** [comment]
testSuite/javalib/time (#2096)

**Comment by gzm0** [comment]
You will also need to detect and run these tests in the JS tools linked test suite: https://github.com/scala-js/scala-js/blob/master/tools/js/src/test/scala/org/scalajs/core/tools/test/js/TestRunner.scala

**Comment by sjrd** [comment]
Oops, indeed!
