### ISSUE TITLE
Remove primitives

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#2269]
This is a meta-issue, collecting all the issues trying to get rid of compiler primitives:
- [x] #1265 - `js.Dynamic.literal`
- [x] #2261 - `j.l.Object.getClass`
- [x] #2262 - `js.Any.fromFunctionN` and `js.ThisFunction.fromFunctionN`
- [x] #2263 - `js.Object.propertiesOf`
- [x] #2264 - `js.Object.hasProperty`
- [x] ~~#2266 - `js.Array.apply`~~
- [x] #2267 - `runtime.environmentInfo`
- [x] #2268 - `BoxedUnit.TYPE` ~~(maybe `BoxedUnit.UNIT`?)~~

What survives the purge?
- `js.Dynamic.newInstance`
- `js.Dictionary.delete`
- `js.typeOf`
- `js.debugger`
- (`js.native`, not really a primitive, it's for compile errors only)
- `BoxedUnit.UNIT` ~~?~~
- `runtime.constructorOf`
- `runtime.linkingInfo`
- `js.Array.apply`

**Comment by sjrd** [comment]
Which makes me think `js.Dictionary.delete` should probably be `js.delete(js.Dynamic, String)`...

**Comment by mrmiywj** [comment]
Maybe I can pick up some of these? Or any ideas about something easier for new bees?

**Comment by sjrd** [comment]
The remaining issues here have non-trivial consequences on a) the design of the language and b) backward compatibility issues. So I don't think they're a good fit to get into the project.

**Comment by sjrd** [comment]
All done.
