### ISSUE TITLE
Things we need to do before 1.0.0

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#2612]
This is a meta-issue to regroup the things we need to do before 1.0.0, so that we have a clear view of what's left, and what we should prioritize to get there.

The most critical parts are language features which will break forward binary compatibility, because they will introduce hacks which we want to get rid of with the jump to 1.0.0:
- [x] [#1381 Add a way to export a top-level method/value](https://github.com/scala-js/scala-js/issues/1381)
- [x] [#1902 Support for static fields in @ScalaJSDefined classes](https://github.com/scala-js/scala-js/issues/1902)
- [x] [#1997 Need @JSSymName(..) annotation](https://github.com/scala-js/scala-js/issues/1997)
- [x] [#2175 Integrating with JS module systems](https://github.com/scala-js/scala-js/issues/2175) (forward compat breaking changes have been done in #2572).

There are also optimizations that we can only do if we change the Infos or the IR, and some cleanup IR changes:
- [ ] [#1961 Honor call-site @inline and @noinline](https://github.com/scala-js/scala-js/issues/1961)
- [ ] [#2227 Remove unused fields](https://github.com/scala-js/scala-js/issues/2227) (this one can only be done _in_ 1.0.0, at least the info change, not before)
- [x] [#2359 Get rid of EmptyTree](https://github.com/scala-js/scala-js/issues/2359)

Anything else?

**Comment by mkotsbak** [comment]
https://github.com/scala-js/scala-js/issues/1991 is merged/closed. Is the reference wrong?

**Comment by sjrd** [comment]
Yes, indeed, the reference was wrong, sorry. I fixed it.

**Comment by andreaTP** [comment]
Thanks a lot for opening this Issue!
As mentioned I really want to get feedback from the community on this.
There are at least 2 sensitive points:
1 - In one here @sjrd will finisch it's Ph.D (congrats)
2 - Larger usage of SJS version 0.6.X will prevent adoption of 1.0 when it will come (i.e. for Sbt)

What we use to say is that SJS IS production ready, so IMO this is time to move towards and start adopting 1.0 version.

I completely understand that there are out many libraries that will be broken, nevertheless more we wait more will come and it will become harder to switch.

If the needed modifications to IR are completely well known and there is no related risk I wish if we can have a 1.0-M to start play with.

**Comment by gzm0** [comment]
#2359 should probably also go in here.

**Comment by mkotsbak** [comment]
What has @sjrd's finishing of his Ph.D to do with this? Does that give him more of less time to spend on this project?

**Comment by sjrd** [comment]
> #2359 should probably also go in here.

Indeed, added.

> What has @sjrd's finishing of his Ph.D to do with this? Does that give him more of less time to spend on this project?

It has virtually nothing to do with it. I don't know why @andreaTP brought this up. Besides, there's no guarantee that I'm finishing in one year. I probably won't; it will probably be a few more months than that.

Now of course, once I graduate, I'll get a job. Whether that job involves maintaining Scala.js or not will have an impact on how much time I can dedicate on it.

**Comment by andreaTP** [comment]
I brought this up because, of course, depending on what you will do for your job, 1.0.0 can be a success or will never happen to be used...

**Comment by sjrd** [comment]
I'm going to close this ticket because it is not useful anymore. Now that we are actually targeting 1.0.0 on the `master` branch, a more accurate view of what we want/need to do before releasing 1.0.0 can be seen in the relevant milestone: https://github.com/scala-js/scala-js/milestone/20
