### ISSUE TITLE
Simplify VirtualFile API

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#3330]
Grab-bag issue for various things. Notably:

- [x] Remove all the different types of `VirtualFiles`, only have a single binary one.
- [x] Make it async (#3635)
- [x] Introduce a custom Output type for the linker.
- [x] Determine future of Node* virtual files (they are currently in the public API, not sure we want this).
- [x] Make mem file API immutable (factories instead of `withMethods`).
- [x] Consider splitting the hierarchy of readable/writable files. We never need both (and probably wont in the future).
- [x] Organize remainder of virtual file types (writable file / binary file for JSEnvs), also see #3656.
- [x] Make as much stuff final as we can.
- [x] Use `java.nio.file.Path` wherever we can. #3658
